# Spring
spring:
  rabbitmq:
    addresses: ${RABBIT_ADDRESSES:digdx01.interno}
    port: ${RABBIT_ADDRESSES:15672}

# Endpoints
endpoints:
  restart:
    enabled: true

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_SERVICE_URLS:http://registry:8761/eureka}

# Logging
logging:
  level:
    com.netflix.discovery: 'INFO'
    org.springframework.cloud: 'INFO'
  path: /oidigital/logs
  file: ${logging.path}/${spring.application.name}_application.log

# Management
management:
  security:
    enabled: false

# Server
server:
  port: 9411
  tomcat:
    accesslog:
      enabled: true
      directory: ${logging.path}/
      prefix: ${spring.application.name}_access_log

---

spring:
  profiles: development
  rabbitmq:
    addresses: digdx01.interno
    port: 15672

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://digdx01.interno:8761/eureka

---

spring:
  profiles: staging

---

spring:
  profiles: production

eureka:
  environment: "Produção"
